/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.util.Date;
import javafx.scene.control.CheckBox;
import javax.swing.JOptionPane;
import model.Car_Info;
import model.Uber_Go;

/**
 *
 * @author Dhaval
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    Car_Info history;
            
    public CreateJPanel(Car_Info history) {
        initComponents();
        this.history=history;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAddCarDetails = new javax.swing.JLabel();
        lblManufacturer = new javax.swing.JLabel();
        lblCarModelName = new javax.swing.JLabel();
        lblCarManuYear = new javax.swing.JLabel();
        lblCarNoSeats = new javax.swing.JLabel();
        lblCarSerialNo = new javax.swing.JLabel();
        lblCarModelNo = new javax.swing.JLabel();
        lblCarMaintenanceDate = new javax.swing.JLabel();
        txtManufacturer = new javax.swing.JTextField();
        txtCarModelName = new javax.swing.JTextField();
        txtCarManuYear = new javax.swing.JTextField();
        txtCarNoSeats = new javax.swing.JTextField();
        txtCarSerialNo = new javax.swing.JTextField();
        txtCarModelNo = new javax.swing.JTextField();
        txtCarMaintenanceDate = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        lblCarAvail = new javax.swing.JLabel();
        txtCarAvial = new javax.swing.JTextField();
        lblCarCity = new javax.swing.JLabel();
        txtCarCity = new javax.swing.JTextField();
        lblUber = new javax.swing.JLabel();

        lblAddCarDetails.setFont(new java.awt.Font("Bauhaus 93", 0, 24)); // NOI18N
        lblAddCarDetails.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAddCarDetails.setText("ADD CAR DETAILS");

        lblManufacturer.setText("Manufacturer:");

        lblCarModelName.setText("Car/Model Name:");

        lblCarManuYear.setText("Manufacture Year:");

        lblCarNoSeats.setText("No. Of Seats:");

        lblCarSerialNo.setText("Car Serial Number:");

        lblCarModelNo.setText("Car Model Number:");

        lblCarMaintenanceDate.setText("Maintenance Date:");

        txtCarMaintenanceDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCarMaintenanceDateActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        lblCarAvail.setText("Availablity:");

        lblCarCity.setText("City:");

        lblUber.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/r3brbjf6y7thcnqhchq2.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblAddCarDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(395, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(516, 516, 516))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblCarAvail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCarModelNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCarCity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCarMaintenanceDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCarSerialNo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCarNoSeats, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCarManuYear, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lblManufacturer, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblCarModelName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)))
                        .addGap(95, 95, 95)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtManufacturer)
                            .addComponent(txtCarModelName)
                            .addComponent(txtCarManuYear)
                            .addComponent(txtCarNoSeats)
                            .addComponent(txtCarSerialNo)
                            .addComponent(txtCarModelNo)
                            .addComponent(txtCarMaintenanceDate, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                            .addComponent(txtCarAvial)
                            .addComponent(txtCarCity))
                        .addGap(343, 343, 343))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblUber, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(398, 398, 398))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUber, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAddCarDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtManufacturer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(txtCarModelName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(txtCarManuYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(txtCarNoSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(txtCarSerialNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(txtCarModelNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(txtCarMaintenanceDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblManufacturer, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(lblCarModelName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(lblCarManuYear, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(lblCarNoSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(lblCarSerialNo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(lblCarModelNo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(lblCarMaintenanceDate, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCarCity)
                    .addComponent(txtCarCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCarAvail)
                    .addComponent(txtCarAvial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addComponent(btnSave)
                .addContainerGap(105, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtCarMaintenanceDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCarMaintenanceDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCarMaintenanceDateActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        
    String manufacturer = txtManufacturer.getText();
    String model_name = txtCarModelName.getText();
    Integer manu_year = Integer.parseInt(txtCarManuYear.getText());
    Integer car_seats = Integer.parseInt(txtCarNoSeats.getText());
    String car_serial_number = txtCarSerialNo.getText();
    String car_model_number = txtCarModelNo.getText();
    String car_maintenance_date = txtCarMaintenanceDate.getText();
    String car_city=txtCarCity.getText();
    String car_avialable = txtCarAvial.getText();
    
    Uber_Go ug = history.addNewCar();
    
    ug.setManufacturer(manufacturer);
    ug.setModel_name(model_name);
    ug.setManu_year(manu_year);
    ug.setCar_seats(car_seats);
    ug.setCar_serial_number(car_serial_number);
    ug.setCar_model_number(car_model_number);
    ug.setCar_maintenance_date(car_maintenance_date);
    ug.setCar_city(car_city);
    ug.setCar_available(car_avialable);
    
    JOptionPane.showMessageDialog(this, "New Car Information Saved");
    
    txtManufacturer.setText("");
    txtCarModelName.setText("");
    txtCarManuYear.setText("");
    txtCarNoSeats.setText("");
    txtCarSerialNo.setText("");
    txtCarModelNo.setText("");
    txtCarMaintenanceDate.setText("");
    txtCarCity.setText("");
    txtCarAvial.setText("");
    
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel lblAddCarDetails;
    private javax.swing.JLabel lblCarAvail;
    private javax.swing.JLabel lblCarCity;
    private javax.swing.JLabel lblCarMaintenanceDate;
    private javax.swing.JLabel lblCarManuYear;
    private javax.swing.JLabel lblCarModelName;
    private javax.swing.JLabel lblCarModelNo;
    private javax.swing.JLabel lblCarNoSeats;
    private javax.swing.JLabel lblCarSerialNo;
    private javax.swing.JLabel lblManufacturer;
    private javax.swing.JLabel lblUber;
    private javax.swing.JTextField txtCarAvial;
    private javax.swing.JTextField txtCarCity;
    private javax.swing.JTextField txtCarMaintenanceDate;
    private javax.swing.JTextField txtCarManuYear;
    private javax.swing.JTextField txtCarModelName;
    private javax.swing.JTextField txtCarModelNo;
    private javax.swing.JTextField txtCarNoSeats;
    private javax.swing.JTextField txtCarSerialNo;
    private javax.swing.JTextField txtManufacturer;
    // End of variables declaration//GEN-END:variables
}
