/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Car_Info;
import model.Uber_Go;

/**
 *
 * @author Dhaval
 */
public class ViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel
     */
    
    Car_Info history;
     
    public ViewJPanel(Car_Info history) {
        initComponents();
        this.history=history;
        
        populateTable();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblViewCar = new javax.swing.JTable();
        btnUpdate = new javax.swing.JButton();
        txtManufacturer = new javax.swing.JTextField();
        lblCarAvail = new javax.swing.JLabel();
        txtCarModelName = new javax.swing.JTextField();
        txtCarAvial = new javax.swing.JTextField();
        txtCarManuYear = new javax.swing.JTextField();
        txtCarNoSeats = new javax.swing.JTextField();
        txtCarSerialNo = new javax.swing.JTextField();
        txtCarModelNo = new javax.swing.JTextField();
        txtCarMaintenanceDate = new javax.swing.JTextField();
        lblManufacturer = new javax.swing.JLabel();
        lblCarModelName = new javax.swing.JLabel();
        lblCarManuYear = new javax.swing.JLabel();
        lblCarNoSeats = new javax.swing.JLabel();
        lblCarSerialNo = new javax.swing.JLabel();
        lblCarModelNo = new javax.swing.JLabel();
        lblCarCity = new javax.swing.JLabel();
        lblCarMaintenanceDate = new javax.swing.JLabel();
        txtCarCity = new javax.swing.JTextField();
        lblUpdatedTimeStamp = new javax.swing.JLabel();
        txtGetTime = new javax.swing.JTextField();
        lblUber = new javax.swing.JLabel();
        lblViewCarDetails = new javax.swing.JLabel();

        tblViewCar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Manufacturer", "Model Name", "Manu Year", "No. of Seats", "Serial Number", "Model Number", "Last Maintainance", "City", "Availablity"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblViewCar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblViewCarMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblViewCar);

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        lblCarAvail.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCarAvail.setText("Availablity:");

        txtCarMaintenanceDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCarMaintenanceDateActionPerformed(evt);
            }
        });

        lblManufacturer.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblManufacturer.setText("Manufacturer:");

        lblCarModelName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCarModelName.setText("Car/Model Name:");

        lblCarManuYear.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCarManuYear.setText("Manufacture Year:");

        lblCarNoSeats.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCarNoSeats.setText("No. Of Seats:");

        lblCarSerialNo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCarSerialNo.setText("Car Serial Number:");

        lblCarModelNo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCarModelNo.setText("Car Model Number:");

        lblCarCity.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCarCity.setText("City:");

        lblCarMaintenanceDate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCarMaintenanceDate.setText("Maintenance Date:");

        lblUpdatedTimeStamp.setText("Last Updated Timestamp:");

        lblUber.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/r3brbjf6y7thcnqhchq2.png"))); // NOI18N

        lblViewCarDetails.setFont(new java.awt.Font("Bauhaus 93", 0, 24)); // NOI18N
        lblViewCarDetails.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblViewCarDetails.setText("VIEW CAR DETAILS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblUpdatedTimeStamp, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtGetTime, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblUber, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(405, 405, 405))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblViewCarDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(217, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblCarNoSeats, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblManufacturer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCarModelName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCarManuYear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCarAvail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtManufacturer)
                    .addComponent(txtCarModelName)
                    .addComponent(txtCarManuYear)
                    .addComponent(txtCarNoSeats)
                    .addComponent(txtCarAvial, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(115, 115, 115)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblCarModelNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCarCity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCarSerialNo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCarMaintenanceDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCarModelNo, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCarSerialNo, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCarMaintenanceDate, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCarCity, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUber, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblViewCarDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate)
                    .addComponent(lblUpdatedTimeStamp)
                    .addComponent(txtGetTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(104, 104, 104)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtManufacturer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblManufacturer, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCarModelName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCarModelName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCarManuYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCarManuYear, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCarNoSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCarNoSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCarSerialNo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCarSerialNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCarModelNo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCarModelNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCarMaintenanceDate, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCarMaintenanceDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCarCity)
                            .addComponent(txtCarCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCarAvail)
                    .addComponent(txtCarAvial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(147, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        
        
        int selectRowIndex = tblViewCar.getSelectedRow();
      
        if(selectRowIndex < 0 ){
            
            JOptionPane.showMessageDialog(this, "Please select the row to be updated.");
            return;
        }
            
        Date thisDate = new Date();
        SimpleDateFormat dateForm = new SimpleDateFormat("MM/dd/Y hh:mm a");
        
        txtGetTime.setText(dateForm.format(thisDate));
        
        //DefaultTableModel model = (DefaultTableModel) tblViewCar.getModel();
        Uber_Go selectedUber = (Uber_Go) history.getHistory().get(selectRowIndex);
        
        selectedUber.setManufacturer(txtManufacturer.getText());
        selectedUber.setModel_name(txtCarModelName.getText());
        selectedUber.setManu_year(Integer.parseInt(txtCarManuYear.getText()));
        selectedUber.setCar_seats(Integer.parseInt(txtCarNoSeats.getText()));
        selectedUber.setCar_serial_number(txtCarSerialNo.getText());
        selectedUber.setCar_model_number(txtCarModelNo.getText());
        selectedUber.setCar_maintenance_date(txtCarMaintenanceDate.getText());
        selectedUber.setCar_city(txtCarCity.getText());
        selectedUber.setCar_available(txtCarAvial.getText());
        
        
        populateTable();
        
        JOptionPane.showMessageDialog(this, "Uber Go has been updated.");
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void tblViewCarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblViewCarMouseClicked
        // TODO add your handling code here:
        
        int selectRowIndex = tblViewCar.getSelectedRow();
      
        /*if(selectRowIndex < 0 ){
            
            JOptionPane.showMessageDialog(this, "Please select the row to be updated.");
            return;
        }*/
        
        
        DefaultTableModel model = (DefaultTableModel) tblViewCar.getModel();
        Uber_Go selectedUber = (Uber_Go) model.getValueAt(selectRowIndex, 0);
        
        
        txtManufacturer.setText(selectedUber.getManufacturer());
        txtCarModelName.setText(selectedUber.getModel_name());
        txtCarManuYear.setText(String.valueOf(selectedUber.getManu_year()));
        txtCarNoSeats.setText(String.valueOf(selectedUber.getCar_seats()));
        txtCarSerialNo.setText(selectedUber.getCar_serial_number());
        txtCarModelNo.setText(selectedUber.getCar_model_number());
        txtCarMaintenanceDate.setText(selectedUber.getCar_maintenance_date());
        txtCarCity.setText(selectedUber.getCar_city());
        txtCarAvial.setText(selectedUber.getCar_available());
        
        
        
    }//GEN-LAST:event_tblViewCarMouseClicked

    private void txtCarMaintenanceDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCarMaintenanceDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCarMaintenanceDateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUpdate;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCarAvail;
    private javax.swing.JLabel lblCarCity;
    private javax.swing.JLabel lblCarMaintenanceDate;
    private javax.swing.JLabel lblCarManuYear;
    private javax.swing.JLabel lblCarModelName;
    private javax.swing.JLabel lblCarModelNo;
    private javax.swing.JLabel lblCarNoSeats;
    private javax.swing.JLabel lblCarSerialNo;
    private javax.swing.JLabel lblManufacturer;
    private javax.swing.JLabel lblUber;
    private javax.swing.JLabel lblUpdatedTimeStamp;
    private javax.swing.JLabel lblViewCarDetails;
    private javax.swing.JTable tblViewCar;
    private javax.swing.JTextField txtCarAvial;
    private javax.swing.JTextField txtCarCity;
    private javax.swing.JTextField txtCarMaintenanceDate;
    private javax.swing.JTextField txtCarManuYear;
    private javax.swing.JTextField txtCarModelName;
    private javax.swing.JTextField txtCarModelNo;
    private javax.swing.JTextField txtCarNoSeats;
    private javax.swing.JTextField txtCarSerialNo;
    private javax.swing.JTextField txtGetTime;
    private javax.swing.JTextField txtManufacturer;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        
        DefaultTableModel model = (DefaultTableModel) tblViewCar.getModel();
        model.setRowCount(0);
        
        for (Uber_Go ug : history.getHistory()){  
            Object[] row = new Object[10];
            row[0] = ug;
            row[1] = ug.getModel_name();
            row[2] = ug.getManu_year();
            row[3] = ug.getCar_seats();
            row[4] = ug.getCar_serial_number();
            row[5] = ug.getCar_model_number();
            row[6] = ug.getCar_maintenance_date();
            row[7] = ug.getCar_city();
            row[8] = ug.getCar_available();
            
            model.addRow(row);
        }
        
    }
}
